// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuCategory = `-- name: CreateMenuCategory :one
INSERT INTO menu_categories (name, description, sort_order)
VALUES ($1, $2, $3)
RETURNING id, name, description, sort_order, created_at, updated_at
`

type CreateMenuCategoryParams struct {
	Name        string
	Description string
	SortOrder   int32
}

func (q *Queries) CreateMenuCategory(ctx context.Context, arg CreateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, createMenuCategory, arg.Name, arg.Description, arg.SortOrder)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (category_id, name, price, description, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, category_id, name, price, description, sort_order, created_at, updated_at
`

type CreateMenuItemParams struct {
	CategoryID  pgtype.UUID
	Name        string
	Price       string
	Description string
	SortOrder   int32
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.CategoryID,
		arg.Name,
		arg.Price,
		arg.Description,
		arg.SortOrder,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenuCategory = `-- name: DeleteMenuCategory :exec
DELETE FROM menu_categories WHERE id = $1
`

func (q *Queries) DeleteMenuCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuCategory, id)
	return err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const deleteMenuItemsByCategoryID = `-- name: DeleteMenuItemsByCategoryID :exec
DELETE FROM menu_items WHERE category_id = $1
`

func (q *Queries) DeleteMenuItemsByCategoryID(ctx context.Context, categoryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItemsByCategoryID, categoryID)
	return err
}

const getMenuCategoryByID = `-- name: GetMenuCategoryByID :one
SELECT id, name, description, sort_order, created_at, updated_at FROM menu_categories WHERE id = $1
`

func (q *Queries) GetMenuCategoryByID(ctx context.Context, id pgtype.UUID) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, getMenuCategoryByID, id)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllMenuItems = `-- name: ListAllMenuItems :many
SELECT id, category_id, name, price, description, sort_order, created_at, updated_at FROM menu_items ORDER BY sort_order ASC
`

func (q *Queries) ListAllMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listAllMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuCategories = `-- name: ListMenuCategories :many
SELECT id, name, description, sort_order, created_at, updated_at FROM menu_categories ORDER BY sort_order ASC
`

func (q *Queries) ListMenuCategories(ctx context.Context) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByCategoryID = `-- name: ListMenuItemsByCategoryID :many
SELECT id, category_id, name, price, description, sort_order, created_at, updated_at FROM menu_items WHERE category_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListMenuItemsByCategoryID(ctx context.Context, categoryID pgtype.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuCategory = `-- name: UpdateMenuCategory :one
UPDATE menu_categories
SET name = $2, description = $3, sort_order = $4
WHERE id = $1
RETURNING id, name, description, sort_order, created_at, updated_at
`

type UpdateMenuCategoryParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	SortOrder   int32
}

func (q *Queries) UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, updateMenuCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET name = $2, price = $3, description = $4, sort_order = $5
WHERE id = $1
RETURNING id, category_id, name, price, description, sort_order, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID          pgtype.UUID
	Name        string
	Price       string
	Description string
	SortOrder   int32
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Description,
		arg.SortOrder,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
