// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Shop struct {
	ID          pgtype.UUID
	Name        string
	Address     string
	OpeningTime pgtype.Time
	ClosingTime pgtype.Time
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Staff struct {
	ID        pgtype.UUID
	ShopID    pgtype.UUID
	Name      string
	Role      string
	Bio       string
	ImageUrl  string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type StaffSchedule struct {
	ID        pgtype.UUID
	StaffID   pgtype.UUID
	DayOfWeek int32
	StartTime pgtype.Time
	EndTime   pgtype.Time
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
