// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shop struct {
	ID          pgtype.UUID
	Name        string
	Address     string
	OpeningTime pgtype.Time
	ClosingTime pgtype.Time
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
