// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShopByID = `-- name: GetShopByID :one
SELECT id, name, address, opening_time, closing_time, created_at, updated_at FROM shops WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id pgtype.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.OpeningTime,
		&i.ClosingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShops = `-- name: ListShops :many
SELECT id, name, address, opening_time, closing_time, created_at, updated_at FROM shops
`

func (q *Queries) ListShops(ctx context.Context) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.OpeningTime,
			&i.ClosingTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type UpdateShopParams struct {
	ID          pgtype.UUID
	Name        string
	Address     string
	OpeningTime pgtype.Time
	ClosingTime pgtype.Time
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops SET name = $2, address = $3, opening_time = $4, closing_time = $5 WHERE id = $1 RETURNING id, name, address, opening_time, closing_time, created_at, updated_at
`

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.OpeningTime,
		arg.ClosingTime,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.OpeningTime,
		&i.ClosingTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
