// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_profile_draft.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfileDraft = `-- name: CreateProfileDraft :one
INSERT INTO staff_profile_drafts (staff_id, name, role, bio, image_url, image_crop_position, status)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type CreateProfileDraftParams struct {
	StaffID           pgtype.UUID
	Name              string
	Role              string
	Bio               string
	ImageUrl          string
	ImageCropPosition string
	Status            string
}

func (q *Queries) CreateProfileDraft(ctx context.Context, arg CreateProfileDraftParams) (StaffProfileDraft, error) {
	row := q.db.QueryRow(ctx, createProfileDraft,
		arg.StaffID,
		arg.Name,
		arg.Role,
		arg.Bio,
		arg.ImageUrl,
		arg.ImageCropPosition,
		arg.Status,
	)
	var i StaffProfileDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfileDraft = `-- name: DeleteProfileDraft :exec
DELETE FROM staff_profile_drafts WHERE id = $1
`

func (q *Queries) DeleteProfileDraft(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileDraft, id)
	return err
}

const getProfileDraftByID = `-- name: GetProfileDraftByID :one
SELECT id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_profile_drafts WHERE id = $1
`

func (q *Queries) GetProfileDraftByID(ctx context.Context, id pgtype.UUID) (StaffProfileDraft, error) {
	row := q.db.QueryRow(ctx, getProfileDraftByID, id)
	var i StaffProfileDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileDraftByStaffID = `-- name: GetProfileDraftByStaffID :one
SELECT id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_profile_drafts WHERE staff_id = $1 AND status IN ('draft', 'pending') ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetProfileDraftByStaffID(ctx context.Context, staffID pgtype.UUID) (StaffProfileDraft, error) {
	row := q.db.QueryRow(ctx, getProfileDraftByStaffID, staffID)
	var i StaffProfileDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingProfileDrafts = `-- name: ListPendingProfileDrafts :many
SELECT id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_profile_drafts WHERE status = 'pending' ORDER BY submitted_at ASC
`

func (q *Queries) ListPendingProfileDrafts(ctx context.Context) ([]StaffProfileDraft, error) {
	rows, err := q.db.Query(ctx, listPendingProfileDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffProfileDraft
	for rows.Next() {
		var i StaffProfileDraft
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.Name,
			&i.Role,
			&i.Bio,
			&i.ImageUrl,
			&i.ImageCropPosition,
			&i.Status,
			&i.AdminComment,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewProfileDraft = `-- name: ReviewProfileDraft :one
UPDATE staff_profile_drafts SET status = $2, admin_comment = $3, reviewed_at = NOW() WHERE id = $1 RETURNING id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type ReviewProfileDraftParams struct {
	ID           pgtype.UUID
	Status       string
	AdminComment string
}

func (q *Queries) ReviewProfileDraft(ctx context.Context, arg ReviewProfileDraftParams) (StaffProfileDraft, error) {
	row := q.db.QueryRow(ctx, reviewProfileDraft, arg.ID, arg.Status, arg.AdminComment)
	var i StaffProfileDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitProfileDraft = `-- name: SubmitProfileDraft :one
UPDATE staff_profile_drafts SET status = 'pending', submitted_at = NOW() WHERE id = $1 RETURNING id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

func (q *Queries) SubmitProfileDraft(ctx context.Context, id pgtype.UUID) (StaffProfileDraft, error) {
	row := q.db.QueryRow(ctx, submitProfileDraft, id)
	var i StaffProfileDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileDraft = `-- name: UpdateProfileDraft :one
UPDATE staff_profile_drafts
SET name = $2, role = $3, bio = $4, image_url = $5, image_crop_position = $6, status = $7
WHERE id = $1 RETURNING id, staff_id, name, role, bio, image_url, image_crop_position, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type UpdateProfileDraftParams struct {
	ID                pgtype.UUID
	Name              string
	Role              string
	Bio               string
	ImageUrl          string
	ImageCropPosition string
	Status            string
}

func (q *Queries) UpdateProfileDraft(ctx context.Context, arg UpdateProfileDraftParams) (StaffProfileDraft, error) {
	row := q.db.QueryRow(ctx, updateProfileDraft,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Bio,
		arg.ImageUrl,
		arg.ImageCropPosition,
		arg.Status,
	)
	var i StaffProfileDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
