// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_refresh_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO staff_refresh_tokens (staff_id, token, expires_at)
VALUES ($1, $2, $3) RETURNING id, staff_id, token, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	StaffID   pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (StaffRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.StaffID, arg.Token, arg.ExpiresAt)
	var i StaffRefreshToken
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM staff_refresh_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM staff_refresh_tokens WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const deleteRefreshTokensByStaffID = `-- name: DeleteRefreshTokensByStaffID :exec
DELETE FROM staff_refresh_tokens WHERE staff_id = $1
`

func (q *Queries) DeleteRefreshTokensByStaffID(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByStaffID, staffID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, staff_id, token, expires_at, created_at FROM staff_refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (StaffRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i StaffRefreshToken
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
