// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffAccount = `-- name: CreateStaffAccount :one
INSERT INTO staff_accounts (staff_id, username, password_hash)
VALUES ($1, $2, $3) RETURNING id, staff_id, username, password_hash, created_at, updated_at
`

type CreateStaffAccountParams struct {
	StaffID      pgtype.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) CreateStaffAccount(ctx context.Context, arg CreateStaffAccountParams) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, createStaffAccount, arg.StaffID, arg.Username, arg.PasswordHash)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaffAccount = `-- name: DeleteStaffAccount :exec
DELETE FROM staff_accounts WHERE id = $1
`

func (q *Queries) DeleteStaffAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaffAccount, id)
	return err
}

const getStaffAccountByStaffID = `-- name: GetStaffAccountByStaffID :one
SELECT id, staff_id, username, password_hash, created_at, updated_at FROM staff_accounts WHERE staff_id = $1
`

func (q *Queries) GetStaffAccountByStaffID(ctx context.Context, staffID pgtype.UUID) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, getStaffAccountByStaffID, staffID)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffAccountByUsername = `-- name: GetStaffAccountByUsername :one
SELECT id, staff_id, username, password_hash, created_at, updated_at FROM staff_accounts WHERE username = $1
`

func (q *Queries) GetStaffAccountByUsername(ctx context.Context, username string) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, getStaffAccountByUsername, username)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffAccounts = `-- name: ListStaffAccounts :many
SELECT id, staff_id, username, password_hash, created_at, updated_at FROM staff_accounts ORDER BY created_at ASC
`

func (q *Queries) ListStaffAccounts(ctx context.Context) ([]StaffAccount, error) {
	rows, err := q.db.Query(ctx, listStaffAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffAccount
	for rows.Next() {
		var i StaffAccount
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffAccount = `-- name: UpdateStaffAccount :one
UPDATE staff_accounts SET username = $2, password_hash = $3 WHERE id = $1 RETURNING id, staff_id, username, password_hash, created_at, updated_at
`

type UpdateStaffAccountParams struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) UpdateStaffAccount(ctx context.Context, arg UpdateStaffAccountParams) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, updateStaffAccount, arg.ID, arg.Username, arg.PasswordHash)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
