// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, shop_id, name, role, bio, image_url, sort_order, created_at, updated_at FROM staffs WHERE id = $1
`

func (q *Queries) GetStaffByID(ctx context.Context, id pgtype.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSchedules = `-- name: ListAllSchedules :many
SELECT id, staff_id, day_of_week, start_time, end_time, created_at, updated_at FROM staff_schedules ORDER BY staff_id, day_of_week ASC
`

func (q *Queries) ListAllSchedules(ctx context.Context) ([]StaffSchedule, error) {
	rows, err := q.db.Query(ctx, listAllSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffSchedule
	for rows.Next() {
		var i StaffSchedule
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByStaffID = `-- name: ListSchedulesByStaffID :many
SELECT id, staff_id, day_of_week, start_time, end_time, created_at, updated_at FROM staff_schedules WHERE staff_id = $1 ORDER BY day_of_week ASC
`

func (q *Queries) ListSchedulesByStaffID(ctx context.Context, staffID pgtype.UUID) ([]StaffSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByStaffID, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffSchedule
	for rows.Next() {
		var i StaffSchedule
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffs = `-- name: ListStaffs :many
SELECT id, shop_id, name, role, bio, image_url, sort_order, created_at, updated_at FROM staffs ORDER BY sort_order ASC
`

func (q *Queries) ListStaffs(ctx context.Context) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Role,
			&i.Bio,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffsByShopID = `-- name: ListStaffsByShopID :many
SELECT id, shop_id, name, role, bio, image_url, sort_order, created_at, updated_at FROM staffs WHERE shop_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListStaffsByShopID(ctx context.Context, shopID pgtype.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffsByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Role,
			&i.Bio,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
