// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_schedule_draft.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduleDraft = `-- name: CreateScheduleDraft :one
INSERT INTO staff_schedule_drafts (staff_id, status)
VALUES ($1, $2) RETURNING id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type CreateScheduleDraftParams struct {
	StaffID pgtype.UUID
	Status  string
}

func (q *Queries) CreateScheduleDraft(ctx context.Context, arg CreateScheduleDraftParams) (StaffScheduleDraft, error) {
	row := q.db.QueryRow(ctx, createScheduleDraft, arg.StaffID, arg.Status)
	var i StaffScheduleDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduleDraftItem = `-- name: CreateScheduleDraftItem :one
INSERT INTO staff_schedule_draft_items (draft_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4) RETURNING id, draft_id, day_of_week, start_time, end_time
`

type CreateScheduleDraftItemParams struct {
	DraftID   pgtype.UUID
	DayOfWeek int32
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

func (q *Queries) CreateScheduleDraftItem(ctx context.Context, arg CreateScheduleDraftItemParams) (StaffScheduleDraftItem, error) {
	row := q.db.QueryRow(ctx, createScheduleDraftItem,
		arg.DraftID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i StaffScheduleDraftItem
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteScheduleDraft = `-- name: DeleteScheduleDraft :exec
DELETE FROM staff_schedule_drafts WHERE id = $1
`

func (q *Queries) DeleteScheduleDraft(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleDraft, id)
	return err
}

const deleteScheduleDraftItems = `-- name: DeleteScheduleDraftItems :exec
DELETE FROM staff_schedule_draft_items WHERE draft_id = $1
`

func (q *Queries) DeleteScheduleDraftItems(ctx context.Context, draftID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleDraftItems, draftID)
	return err
}

const getScheduleDraftByID = `-- name: GetScheduleDraftByID :one
SELECT id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_schedule_drafts WHERE id = $1
`

func (q *Queries) GetScheduleDraftByID(ctx context.Context, id pgtype.UUID) (StaffScheduleDraft, error) {
	row := q.db.QueryRow(ctx, getScheduleDraftByID, id)
	var i StaffScheduleDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleDraftByStaffID = `-- name: GetScheduleDraftByStaffID :one
SELECT id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_schedule_drafts WHERE staff_id = $1 AND status IN ('draft', 'pending', 'rejected') ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetScheduleDraftByStaffID(ctx context.Context, staffID pgtype.UUID) (StaffScheduleDraft, error) {
	row := q.db.QueryRow(ctx, getScheduleDraftByStaffID, staffID)
	var i StaffScheduleDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedScheduleDrafts = `-- name: ListApprovedScheduleDrafts :many
SELECT id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_schedule_drafts WHERE status = 'approved' ORDER BY reviewed_at ASC
`

func (q *Queries) ListApprovedScheduleDrafts(ctx context.Context) ([]StaffScheduleDraft, error) {
	rows, err := q.db.Query(ctx, listApprovedScheduleDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffScheduleDraft
	for rows.Next() {
		var i StaffScheduleDraft
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.Status,
			&i.AdminComment,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingScheduleDrafts = `-- name: ListPendingScheduleDrafts :many
SELECT id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at FROM staff_schedule_drafts WHERE status = 'pending' ORDER BY submitted_at ASC
`

func (q *Queries) ListPendingScheduleDrafts(ctx context.Context) ([]StaffScheduleDraft, error) {
	rows, err := q.db.Query(ctx, listPendingScheduleDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffScheduleDraft
	for rows.Next() {
		var i StaffScheduleDraft
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.Status,
			&i.AdminComment,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleDraftItems = `-- name: ListScheduleDraftItems :many
SELECT id, draft_id, day_of_week, start_time, end_time FROM staff_schedule_draft_items WHERE draft_id = $1 ORDER BY day_of_week ASC
`

func (q *Queries) ListScheduleDraftItems(ctx context.Context, draftID pgtype.UUID) ([]StaffScheduleDraftItem, error) {
	rows, err := q.db.Query(ctx, listScheduleDraftItems, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffScheduleDraftItem
	for rows.Next() {
		var i StaffScheduleDraftItem
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewScheduleDraft = `-- name: ReviewScheduleDraft :one
UPDATE staff_schedule_drafts SET status = $2, admin_comment = $3, reviewed_at = NOW() WHERE id = $1 AND updated_at = $4 RETURNING id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type ReviewScheduleDraftParams struct {
	ID           pgtype.UUID
	Status       string
	AdminComment string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ReviewScheduleDraft(ctx context.Context, arg ReviewScheduleDraftParams) (StaffScheduleDraft, error) {
	row := q.db.QueryRow(ctx, reviewScheduleDraft,
		arg.ID,
		arg.Status,
		arg.AdminComment,
		arg.UpdatedAt,
	)
	var i StaffScheduleDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitScheduleDraft = `-- name: SubmitScheduleDraft :one
UPDATE staff_schedule_drafts SET status = 'pending', submitted_at = NOW() WHERE id = $1 AND updated_at = $2 RETURNING id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type SubmitScheduleDraftParams struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SubmitScheduleDraft(ctx context.Context, arg SubmitScheduleDraftParams) (StaffScheduleDraft, error) {
	row := q.db.QueryRow(ctx, submitScheduleDraft, arg.ID, arg.UpdatedAt)
	var i StaffScheduleDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduleDraftStatus = `-- name: UpdateScheduleDraftStatus :one
UPDATE staff_schedule_drafts SET status = $2 WHERE id = $1 AND updated_at = $3 RETURNING id, staff_id, status, admin_comment, submitted_at, reviewed_at, created_at, updated_at
`

type UpdateScheduleDraftStatusParams struct {
	ID        pgtype.UUID
	Status    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateScheduleDraftStatus(ctx context.Context, arg UpdateScheduleDraftStatusParams) (StaffScheduleDraft, error) {
	row := q.db.QueryRow(ctx, updateScheduleDraftStatus, arg.ID, arg.Status, arg.UpdatedAt)
	var i StaffScheduleDraft
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Status,
		&i.AdminComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
