// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, shop_id, name, role, bio, image_url, image_crop_position, sort_order, created_at, updated_at FROM staffs WHERE id = $1
`

func (q *Queries) GetStaffByID(ctx context.Context, id pgtype.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSchedules = `-- name: ListAllSchedules :many
SELECT id, staff_id, day_of_week, start_time, end_time, created_at, updated_at FROM staff_schedules ORDER BY staff_id, day_of_week ASC
`

func (q *Queries) ListAllSchedules(ctx context.Context) ([]StaffSchedule, error) {
	rows, err := q.db.Query(ctx, listAllSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffSchedule
	for rows.Next() {
		var i StaffSchedule
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByStaffID = `-- name: ListSchedulesByStaffID :many
SELECT id, staff_id, day_of_week, start_time, end_time, created_at, updated_at FROM staff_schedules WHERE staff_id = $1 ORDER BY day_of_week ASC
`

func (q *Queries) ListSchedulesByStaffID(ctx context.Context, staffID pgtype.UUID) ([]StaffSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByStaffID, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffSchedule
	for rows.Next() {
		var i StaffSchedule
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffs = `-- name: ListStaffs :many
SELECT id, shop_id, name, role, bio, image_url, image_crop_position, sort_order, created_at, updated_at FROM staffs ORDER BY sort_order ASC
`

func (q *Queries) ListStaffs(ctx context.Context) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Role,
			&i.Bio,
			&i.ImageUrl,
			&i.ImageCropPosition,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffsByShopID = `-- name: ListStaffsByShopID :many
SELECT id, shop_id, name, role, bio, image_url, image_crop_position, sort_order, created_at, updated_at FROM staffs WHERE shop_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListStaffsByShopID(ctx context.Context, shopID pgtype.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffsByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Role,
			&i.Bio,
			&i.ImageUrl,
			&i.ImageCropPosition,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type CreateStaffParams struct {
	ShopID            pgtype.UUID
	Name              string
	Role              string
	Bio               string
	ImageUrl          string
	ImageCropPosition string
	SortOrder         int32
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staffs (shop_id, name, role, bio, image_url, image_crop_position, sort_order) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, shop_id, name, role, bio, image_url, image_crop_position, sort_order, created_at, updated_at
`

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.ShopID,
		arg.Name,
		arg.Role,
		arg.Bio,
		arg.ImageUrl,
		arg.ImageCropPosition,
		arg.SortOrder,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type UpdateStaffParams struct {
	ID                pgtype.UUID
	Name              string
	Role              string
	Bio               string
	ImageUrl          string
	ImageCropPosition string
	SortOrder         int32
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staffs SET name = $2, role = $3, bio = $4, image_url = $5, image_crop_position = $6, sort_order = $7 WHERE id = $1 RETURNING id, shop_id, name, role, bio, image_url, image_crop_position, sort_order, created_at, updated_at
`

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Bio,
		arg.ImageUrl,
		arg.ImageCropPosition,
		arg.SortOrder,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Role,
		&i.Bio,
		&i.ImageUrl,
		&i.ImageCropPosition,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staffs WHERE id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaff, id)
	return err
}

const deleteSchedulesByStaffID = `-- name: DeleteSchedulesByStaffID :exec
DELETE FROM staff_schedules WHERE staff_id = $1
`

func (q *Queries) DeleteSchedulesByStaffID(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedulesByStaffID, staffID)
	return err
}

type CreateScheduleParams struct {
	StaffID   pgtype.UUID
	DayOfWeek int32
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO staff_schedules (staff_id, day_of_week, start_time, end_time) VALUES ($1, $2, $3, $4) RETURNING id, staff_id, day_of_week, start_time, end_time, created_at, updated_at
`

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (StaffSchedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.StaffID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i StaffSchedule
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
